services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: online_store
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
      - ./init/mysql:/docker-entrypoint-initdb.d
    networks:
      - datanika
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "SA_Password1!"
    ports:
      - "1433:1433"
    volumes:
      - mssqldata:/var/opt/mssql
    networks:
      - datanika
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "SA_Password1!" -C -Q "SELECT 1" || exit 1
      interval: 5s
      timeout: 5s
      retries: 10

  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - datanika
    healthcheck:
      test: mongosh --eval "db.runCommand('ping')" --quiet
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mysqldata:
  mssqldata:
  mongodata:

networks:
  datanika:
    external: true
    name: datanika_default
